=== samzek/sentiment_analysis/prgVerucchiZecchini/results/tweet_collection.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="tweet_collection">
    <xs:complexType>
	    <xs:sequence>
		    <xs:element ref="tweet" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element ref="Precision_recall" minOccurs="1" maxOccurs="1"/>
	    </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="tweet">
    <xs:complexType>
	    <xs:sequence>
		    <xs:element name="Original_tweet" type="xs:string"/>
		    <xs:element name="Translate_tweet" type="xs:string"/>
		    <xs:element name="Sentiment_nostem" type="xs:string"/>
		    <xs:element name="Sentiment_stem" type="xs:string"/>
	    </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="Precision_recall">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="POSITIVE" minOccurs="0"/>
            <xs:element ref="NEGATIVE" minOccurs="0"/>
            <xs:element ref="POSITIVE_STEMMED" minOccurs="0"/>
            <xs:element ref="NEGATIVE_STEMMED" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="POSITIVE">
    <xs:complexType>
        <xs:sequence>
        <xs:element name="Precision" type="xs:string"/>
        <xs:element name="Recall" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:element name="NEGATIVE">
    <xs:complexType>
        <xs:sequence>
        <xs:element name="Precision" type="xs:string"/>
        <xs:element name="Recall" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:element name="POSITIVE_STEMMED">
    <xs:complexType>
        <xs:sequence>
        <xs:element name="Precision" type="xs:string"/>
        <xs:element name="Recall" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
<xs:element name="NEGATIVE_STEMMED">
    <xs:complexType>
        <xs:sequence>
        <xs:element name="Precision" type="xs:string"/>
        <xs:element name="Recall" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== samzek/sentiment_analysis/prgVerucchiZecchini/results/song.xml
<?xml version='1.0' encoding='UTF-8'?>
<tweet_collection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="tweet_collection.xsd">
  <tweet>
    <Original_tweet>hey i just met you, and this is crazy, but here's my numer so call me maybe </Original_tweet>
    <Translate_tweet>hey i just met you, and this is crazy, but here's my numer so call me maybe </Translate_tweet>
    <Sentiment_nostem>NEGATIVE</Sentiment_nostem>
    <Sentiment_stem>POSITIVE</Sentiment_stem>
    <Expected>POSITIVE</Expected>
  </tweet>
  <Precision_recall>
    <POSITIVE>
      <Precision>0.0%</Precision>
      <Recall>0.0%</Recall>
    </POSITIVE>
    <POSITIVE_STEMMED>
      <Precision>100.0%</Precision>
      <Recall>100.0%</Recall>
    </POSITIVE_STEMMED>
  </Precision_recall>
</tweet_collection>

=== samzek/sentiment_analysis/prgVerucchiZecchini/results/prova.xml
<?xml version='1.0' encoding='UTF-8'?>
<tweet_collection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="tweet_collection.xsd">
  <tweet>
    <Original_tweet>questa Ã¨ una prova </Original_tweet>
    <Translate_tweet>this is a test</Translate_tweet>
    <Sentiment_nostem>POSITIVE</Sentiment_nostem>
    <Sentiment_stem>POSITIVE</Sentiment_stem>
    <Expected>POSITIVE</Expected>
  </tweet>
  <Precision_recall>
    <POSITIVE>
      <Precision>100.0%</Precision>
      <Recall>100.0%</Recall>
    </POSITIVE>
    <POSITIVE_STEMMED>
      <Precision>100.0%</Precision>
      <Recall>100.0%</Recall>
    </POSITIVE_STEMMED>
  </Precision_recall>
</tweet_collection>

=== samzek/sentiment_analysis/prgVerucchiZecchini/results/tweet.xml
<?xml version='1.0' encoding='UTF-8'?>
<tweet_collection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="tweet_collection.xsd">
  <tweet>
    <Original_tweet>oggi sono davvero tristissima </Original_tweet>
    <Translate_tweet>Today I am really sad</Translate_tweet>
    <Sentiment_nostem>NEGATIVE</Sentiment_nostem>
    <Sentiment_stem>NEGATIVE</Sentiment_stem>
  </tweet>
  <tweet>
    <Original_tweet>this is a terrbile test! </Original_tweet>
    <Translate_tweet>this is a terrbile test! </Translate_tweet>
    <Sentiment_nostem>POSITIVE</Sentiment_nostem>
    <Sentiment_stem>POSITIVE</Sentiment_stem>
  </tweet>
</tweet_collection>
